baseurl = "https://master.d3vb6a7ts4cf2a.amplifyapp.com"
theme = "../.."
builddrafts = false
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
# imagedir = "static/img"
author = "Alexis Tacnet"
title = "Cocoa Enhanced"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2015-{year} Nishanth Shanmugham"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = false
progressively = false
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
social_banner = "img/banner.png"
usesmallsummarycard = false
posts_navigation = false
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

